/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.validation;

import de.thm.evolvedb.graph.BinaryDataTypes;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.BinaryTypes}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BinaryTypesValidator {
	boolean validate();

	boolean validateType(BinaryDataTypes value);

	boolean validateMinLength(int value);

	boolean validateMaxLength(int value);
}
