/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.validation;

import de.thm.evolvedb.graph.EdgeLabel;
import de.thm.evolvedb.graph.NodeType;
import de.thm.evolvedb.graph.Property;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.EdgeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeTypeValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateLabels(EList<EdgeLabel> value);

	boolean validateProperties(EList<Property> value);

	boolean validateSrc(NodeType value);

	boolean validateTgt(NodeType value);
}
