/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.validation;

import de.thm.evolvedb.graph.Constraint;
import de.thm.evolvedb.graph.Label;
import de.thm.evolvedb.graph.Property;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.Label}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LabelValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateProperties(EList<Property> value);

	boolean validateSuperType(EList<Label> value);

	boolean validateConstraints(EList<Constraint> value);
}
