/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.validation;

import de.thm.evolvedb.graph.NumericDataTypes;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.NumericType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NumericTypeValidator {
	boolean validate();

	boolean validateType(NumericDataTypes value);

	boolean validateIntegralPart(int value);

	boolean validateFractionalPart(int value);
}
