/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.validation;

import de.thm.evolvedb.graph.GraphItem;
import de.thm.evolvedb.graph.GraphType;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.PropertyGraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyGraphValidator {
	boolean validate();

	boolean validateClosed(boolean value);

	boolean validateGraphtype(GraphType value);

	boolean validateItems(EList<GraphItem> value);

	boolean validateName(String value);

	boolean validateLocation(String value);
}
