/**
 *
 * $Id$
 */
package de.thm.evolvedb.graph.validation;

import de.thm.evolvedb.graph.TemporalDataTypes;

/**
 * A sample validator interface for {@link de.thm.evolvedb.graph.TemporalTypes}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TemporalTypesValidator {
	boolean validate();

	boolean validateType(TemporalDataTypes value);
}
