<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="createForeignKey_IN_Table_changeForeignKey_referencedTable_TO_Table"
      nsURI="http://cdapackage/createForeignKey_IN_Table/changeForeignKey_referencedTable_TO_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#New_Selected:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=Name _  -> " lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnUpdate=OnUpdate _  -> "
          lowerBound="1" eType="ecore:EEnum http://www.thm.de/mdde#//Referential_Action"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnDelete=OnDelete _  -> "
          lowerBound="1" eType="ecore:EEnum http://www.thm.de/mdde#//Referential_Action"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintName=ConstraintName _  -> "
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/0/Existing1_OldTarget%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing1_OldTarget:Table"/>
  </ecore:EPackage>
  <ecore:EPackage name="changeForeignKey_referencedTable_TO_Table_createForeignKey_IN_Table"
      nsURI="http://cdapackage/changeForeignKey_referencedTable_TO_Table/createForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_New:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/1/OldTarget_Existing1%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_Existing1:Table"/>
  </ecore:EPackage>
</xmi:XMI>
