<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="changeForeignKey_referencedTable_TO_Table_changeForeignKey_referencedTable_TO_Table"
    nsURI="http://cdapackage/changeForeignKey_referencedTable_TO_Table/changeForeignKey_referencedTable_TO_Table/DeleteConflictAtom"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:ForeignKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#//OldTarget_OldTarget%3ATable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:Table"/>
</ecore:EPackage>
