<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="changeForeignKey_referencedKeyColumn_TO_PrimaryKey_deleteForeignKey_IN_Table"
      nsURI="http://cdapackage/changeForeignKey_referencedKeyColumn_TO_PrimaryKey/deleteForeignKey_IN_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_Existing:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/0/Selected_ToBeDeleted%3AForeignKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_ToBeDeleted:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/0/OldTarget_Existing%3APrimaryKey"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deleteForeignKey_IN_Table_changeForeignKey_referencedKeyColumn_TO_PrimaryKey"
      nsURI="http://cdapackage/deleteForeignKey_IN_Table/changeForeignKey_referencedKeyColumn_TO_PrimaryKey/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_Selected:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/1/Existing_OldTarget%3APrimaryKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing_OldTarget:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/1/%23ToBeDeleted_Selected%3AForeignKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
