<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="changeForeignKey_referencedKeyColumn_TO_PrimaryKey_deleteForeignKey_IN_Table"
    nsURI="http://cdapackage/changeForeignKey_referencedKeyColumn_TO_PrimaryKey/deleteForeignKey_IN_Table/CreateEdgeDeleteNodeConflictReason"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#OldTarget_Existing:PrimaryKey#">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#//%23Selected_ToBeDeleted%3AForeignKey%23"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="#Selected_ToBeDeleted:ForeignKey#">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
        eType="#//%23OldTarget_Existing%3APrimaryKey%23"/>
  </eClassifiers>
</ecore:EPackage>
