<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="createTable_IN_Database_Schema_deleteTable_IN_Database_Schema"
      nsURI="http://cdapackage/createTable_IN_Database_Schema/deleteTable_IN_Database_Schema/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#New_ToBeDeleted:Table#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=Name _  " lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#schema#" eType="#/0/Selected_Selected%3ADatabase_Schema"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Database_Schema">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entites#" eType="#/0/%23New_ToBeDeleted%3ATable%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deleteTable_IN_Database_Schema_createTable_IN_Database_Schema"
      nsURI="http://cdapackage/deleteTable_IN_Database_Schema/createTable_IN_Database_Schema/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_New:Table#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#schema#" eType="#/1/Selected_Selected%3ADatabase_Schema"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Database_Schema">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entites#" eType="#/1/%23ToBeDeleted_New%3ATable%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
