<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="createPrimaryKey_IN_Table_deletePrimaryKey_IN_Table" nsURI="http://cdapackage/createPrimaryKey_IN_Table/deletePrimaryKey_IN_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#New_ToBeDeleted:PrimaryKey#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=Name _  " lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/0/Selected_Selected%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/0/%23New_ToBeDeleted%3APrimaryKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deletePrimaryKey_IN_Table_createPrimaryKey_IN_Table" nsURI="http://cdapackage/deletePrimaryKey_IN_Table/createPrimaryKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_New:PrimaryKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/1/Selected_Selected%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/1/%23ToBeDeleted_New%3APrimaryKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
