<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="removeFromPrimaryKey_referencedBy_ForeignKey_removeFromPrimaryKey_referencedBy_ForeignKey"
    nsURI="http://cdapackage/removeFromPrimaryKey_referencedBy_ForeignKey/removeFromPrimaryKey_referencedBy_ForeignKey/DeleteConflictAtom"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:ForeignKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
        eType="#//Selected_Selected%3APrimaryKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:PrimaryKey"/>
</ecore:EPackage>
