<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="changeForeignKey_referencedKeyColumn_TO_PrimaryKey_changeForeignKey_referencedKeyColumn_TO_PrimaryKey"
    nsURI="http://cdapackage/changeForeignKey_referencedKeyColumn_TO_PrimaryKey/changeForeignKey_referencedKeyColumn_TO_PrimaryKey/DeleteConflictAtom"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:ForeignKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
        eType="#//OldTarget_OldTarget%3APrimaryKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:PrimaryKey"/>
</ecore:EPackage>
