<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="moveColumn_FROM_Table_columns_TO_Table_Table_moveForeignKey_FROM_Table_columns_TO_Table_Table"
      nsURI="http://cdapackage/moveColumn_FROM_Table_columns_TO_Table_Table/moveForeignKey_FROM_Table_columns_TO_Table_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/0/NewSource_OldSource%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NewSource_OldSource:Table"/>
  </ecore:EPackage>
  <ecore:EPackage name="moveForeignKey_FROM_Table_columns_TO_Table_Table_moveColumn_FROM_Table_columns_TO_Table_Table"
      nsURI="http://cdapackage/moveForeignKey_FROM_Table_columns_TO_Table_Table/moveColumn_FROM_Table_columns_TO_Table_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldSource_NewSource:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/1/Selected_Selected%3AForeignKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/1/OldSource_NewSource%3ATable"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="moveForeignKey_FROM_Table_columns_TO_Table_Table_moveColumn_FROM_Table_columns_TO_Table_Table"
      nsURI="http://cdapackage/moveForeignKey_FROM_Table_columns_TO_Table_Table/moveColumn_FROM_Table_columns_TO_Table_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldSource_NewSource:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/2/Selected_Selected%3AForeignKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:ForeignKey"/>
  </ecore:EPackage>
  <ecore:EPackage name="moveForeignKey_FROM_Table_columns_TO_Table_Table_moveColumn_FROM_Table_columns_TO_Table_Table"
      nsURI="http://cdapackage/moveForeignKey_FROM_Table_columns_TO_Table_Table/moveColumn_FROM_Table_columns_TO_Table_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/3/OldSource_NewSource%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldSource_NewSource:Table"/>
  </ecore:EPackage>
</xmi:XMI>
