<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="addToPrimaryKey_referencedBy_ForeignKey_removeFromPrimaryKey_referencedBy_ForeignKey"
      nsURI="http://cdapackage/addToPrimaryKey_referencedBy_ForeignKey/removeFromPrimaryKey_referencedBy_ForeignKey/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="NewTarget_OldTarget:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/0/Selected_Selected%3APrimaryKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/0/NewTarget_OldTarget%3AForeignKey"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="removeFromPrimaryKey_referencedBy_ForeignKey_addToPrimaryKey_referencedBy_ForeignKey"
      nsURI="http://cdapackage/removeFromPrimaryKey_referencedBy_ForeignKey/addToPrimaryKey_referencedBy_ForeignKey/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/1/OldTarget_NewTarget%3AForeignKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_NewTarget:ForeignKey"/>
  </ecore:EPackage>
  <ecore:EPackage name="removeFromPrimaryKey_referencedBy_ForeignKey_addToPrimaryKey_referencedBy_ForeignKey"
      nsURI="http://cdapackage/removeFromPrimaryKey_referencedBy_ForeignKey/addToPrimaryKey_referencedBy_ForeignKey/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/2/OldTarget_NewTarget%3AForeignKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_NewTarget:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/2/Selected_Selected%3APrimaryKey"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="removeFromPrimaryKey_referencedBy_ForeignKey_addToPrimaryKey_referencedBy_ForeignKey"
      nsURI="http://cdapackage/removeFromPrimaryKey_referencedBy_ForeignKey/addToPrimaryKey_referencedBy_ForeignKey/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_NewTarget:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/3/Selected_Selected%3APrimaryKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:PrimaryKey"/>
  </ecore:EPackage>
</xmi:XMI>
