<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="createForeignKey_IN_Table_moveForeignKey_FROM_Table_columns_TO_Table_Table"
      nsURI="http://cdapackage/createForeignKey_IN_Table/moveForeignKey_FROM_Table_columns_TO_Table_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#New_Selected:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=Name _  -> " lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnUpdate=OnUpdate _  -> "
          lowerBound="1" eType="ecore:EEnum http://www.thm.de/mdde#//Referential_Action"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnDelete=OnDelete _  -> "
          lowerBound="1" eType="ecore:EEnum http://www.thm.de/mdde#//Referential_Action"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintName=ConstraintName _  -> "
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/0/Selected_OldSource%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_OldSource:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/0/%23New_Selected%3AForeignKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="moveForeignKey_FROM_Table_columns_TO_Table_Table_createForeignKey_IN_Table"
      nsURI="http://cdapackage/moveForeignKey_FROM_Table_columns_TO_Table_Table/createForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_New:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/1/OldSource_Selected%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldSource_Selected:Table"/>
  </ecore:EPackage>
  <ecore:EPackage name="moveForeignKey_FROM_Table_columns_TO_Table_Table_createForeignKey_IN_Table"
      nsURI="http://cdapackage/moveForeignKey_FROM_Table_columns_TO_Table_Table/createForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_New:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/2/OldSource_Selected%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldSource_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/2/Selected_New%3AForeignKey"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="moveForeignKey_FROM_Table_columns_TO_Table_Table_createForeignKey_IN_Table"
      nsURI="http://cdapackage/moveForeignKey_FROM_Table_columns_TO_Table_Table/createForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldSource_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/3/Selected_New%3AForeignKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_New:ForeignKey"/>
  </ecore:EPackage>
</xmi:XMI>
