<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="removeFromColumn_constraints_ColumnConstraint_removeFromColumn_constraints_ColumnConstraint"
      nsURI="http://cdapackage/removeFromColumn_constraints_ColumnConstraint/removeFromColumn_constraints_ColumnConstraint/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:ColumnConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#column#" eType="#/0/Selected_Selected%3AColumn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Column">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#constraints#" eType="#/0/OldTarget_OldTarget%3AColumnConstraint"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="removeFromColumn_constraints_ColumnConstraint_removeFromColumn_constraints_ColumnConstraint"
      nsURI="http://cdapackage/removeFromColumn_constraints_ColumnConstraint/removeFromColumn_constraints_ColumnConstraint/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:ColumnConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#column#" eType="#/1/Selected_Selected%3AColumn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Column"/>
  </ecore:EPackage>
  <ecore:EPackage name="removeFromColumn_constraints_ColumnConstraint_removeFromColumn_constraints_ColumnConstraint"
      nsURI="http://cdapackage/removeFromColumn_constraints_ColumnConstraint/removeFromColumn_constraints_ColumnConstraint/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:ColumnConstraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#column#" eType="#/2/Selected_Selected%3AColumn"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Column">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#constraints#" eType="#/2/OldTarget_OldTarget%3AColumnConstraint"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="removeFromColumn_constraints_ColumnConstraint_removeFromColumn_constraints_ColumnConstraint"
      nsURI="http://cdapackage/removeFromColumn_constraints_ColumnConstraint/removeFromColumn_constraints_ColumnConstraint/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Column">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#constraints#" eType="#/3/OldTarget_OldTarget%3AColumnConstraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_OldTarget:ColumnConstraint"/>
  </ecore:EPackage>
</xmi:XMI>
