<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="createPrimaryKey_IN_Table_createForeignKey_IN_Table" nsURI="http://cdapackage/createPrimaryKey_IN_Table/createForeignKey_IN_Table/CreateDependencyReason"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#New_Existing:PrimaryKey#">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=Name _  -> " lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
