<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteForeignKey_IN_Table_changeForeignKey_referencedTable_TO_Table"
      nsURI="http://cdapackage/deleteForeignKey_IN_Table/changeForeignKey_referencedTable_TO_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_Selected:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/0/Existing1_OldTarget%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing1_OldTarget:Table"/>
  </ecore:EPackage>
  <ecore:EPackage name="changeForeignKey_referencedTable_TO_Table_deleteForeignKey_IN_Table"
      nsURI="http://cdapackage/changeForeignKey_referencedTable_TO_Table/deleteForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="Selected_ToBeDeleted:ForeignKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/1/OldTarget_Existing1%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OldTarget_Existing1:Table"/>
  </ecore:EPackage>
</xmi:XMI>
