<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deleteForeignKey_IN_Table_moveForeignKey_FROM_Table_columns_TO_Table_Table"
    nsURI="http://cdapackage/deleteForeignKey_IN_Table/moveForeignKey_FROM_Table_columns_TO_Table_Table/DeleteEdgeDeleteNodeDependencyAtom"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_Selected:ForeignKey#"/>
</ecore:EPackage>
