<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moveColumn_FROM_Table_columns_TO_Table_Table_deleteForeignKey_IN_Table"
    nsURI="http://cdapackage/moveColumn_FROM_Table_columns_TO_Table_Table/deleteForeignKey_IN_Table/DeleteEdgeDeleteNodeDependencyReason"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#NewSource_Selected:Table#">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#//%23Selected_ToBeDeleted%3AForeignKey%23"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="#Selected_ToBeDeleted:ForeignKey#">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#//%23NewSource_Selected%3ATable%23"/>
  </eClassifiers>
</ecore:EPackage>
