<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteForeignKey_IN_Table_deleteForeignKey_IN_Table" nsURI="http://cdapackage/deleteForeignKey_IN_Table/deleteForeignKey_IN_Table/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_ToBeDeleted:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/0/Existing_Existing%3APrimaryKey"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/0/Existing1_Existing1%3ATable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/0/Selected_Selected%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing_Existing:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/0/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing1_Existing1:Table"/>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/0/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deleteForeignKey_IN_Table_deleteForeignKey_IN_Table" nsURI="http://cdapackage/deleteForeignKey_IN_Table/deleteForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_ToBeDeleted:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/1/Selected_Selected%3ATable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/1/Existing_Existing%3APrimaryKey"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/1/Existing1_Existing1%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/1/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing_Existing:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/1/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing1_Existing1:Table"/>
  </ecore:EPackage>
  <ecore:EPackage name="deleteForeignKey_IN_Table_deleteForeignKey_IN_Table" nsURI="http://cdapackage/deleteForeignKey_IN_Table/deleteForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_ToBeDeleted:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/2/Existing_Existing%3APrimaryKey"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/2/Existing1_Existing1%3ATable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/2/Selected_Selected%3ATable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing_Existing:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/2/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing1_Existing1:Table"/>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/2/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deleteForeignKey_IN_Table_deleteForeignKey_IN_Table" nsURI="http://cdapackage/deleteForeignKey_IN_Table/deleteForeignKey_IN_Table/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_ToBeDeleted:ForeignKey#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedTable#" eType="#/3/Existing1_Existing1%3ATable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#/3/Selected_Selected%3ATable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedKeyColumn#"
          eType="#/3/Existing_Existing%3APrimaryKey"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing1_Existing1:Table"/>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Table">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/3/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Existing_Existing:PrimaryKey">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#referencedBy#" eType="#/3/%23ToBeDeleted_ToBeDeleted%3AForeignKey%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
