<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="movePrimaryKey_FROM_Table_columns_TO_Table_Table_movePrimaryKey_FROM_Table_columns_TO_Table_Table"
    nsURI="http://cdapackage/movePrimaryKey_FROM_Table_columns_TO_Table_Table/movePrimaryKey_FROM_Table_columns_TO_Table_Table/DeleteConflictAtom"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:PrimaryKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="#table#" eType="#//OldSource_OldSource%3ATable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OldSource_OldSource:Table"/>
</ecore:EPackage>
