<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteColumnConstraint_IN_Constraint_deleteColumnConstraint_IN_Constraint"
      nsURI="http://cdapackage/deleteColumnConstraint_IN_Constraint/deleteColumnConstraint_IN_Constraint/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_ToBeDeleted:ColumnConstraint#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#constraint#" eType="#/0/Selected_Selected%3AConstraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/0/%23ToBeDeleted_ToBeDeleted%3AColumnConstraint%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deleteColumnConstraint_IN_Constraint_deleteColumnConstraint_IN_Constraint"
      nsURI="http://cdapackage/deleteColumnConstraint_IN_Constraint/deleteColumnConstraint_IN_Constraint/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#ToBeDeleted_ToBeDeleted:ColumnConstraint#">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#constraint#" eType="#/1/Selected_Selected%3AConstraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Selected_Selected:Constraint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#columns#" eType="#/1/%23ToBeDeleted_ToBeDeleted%3AColumnConstraint%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
